export {default as DetailPage} from './DetailPage'
export {default as HomePage} from './HomePage'
export {default as LoginPage} from './LoginPage'
export {default as SignupPage} from './SignupPage'
export {default as CustomerFillInfoPage} from './CustomerFillInfoPage'
export {default as PTFillFormPage} from './PTFillFormPage'
export {default as FindCustomerPage} from './FindCustomerPage'